FROM python:3.12-slim

WORKDIR /app

COPY requirements-migrations.txt .
RUN pip install --no-cache-dir -r requirements-migrations.txt

COPY alembic.ini .
COPY migrations ./migrations
COPY scripts ./scripts

CMD ["python", "scripts/run_migrations.py"]
